version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode-filemanager-test
    hostname: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_proxyuser_hdfs_hosts=*
      - CORE_CONF_hadoop_proxyuser_hdfs_groups=*
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_namenode_name_dir=/hadoop/dfs/name
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false
    ports:
      - "9000:9000"   # NameNode IPC port
      - "9870:9870"   # NameNode Web UI port
    volumes:
      - ./test-data:/test-data
      - namenode_data:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode-filemanager-test
    hostname: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_datanode_data_dir=/hadoop/dfs/data
    ports:
      - "9866:9866"   # DataNode data transfer port
      - "9864:9864"   # DataNode HTTP port
    volumes:
      - ./test-data:/test-data
      - datanode_data:/hadoop/dfs/data
    depends_on:
      - namenode

  # Test data initialization container
  test-setup:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-test-setup-filemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    volumes:
      - ./test-data:/test-data
      - ./setup-test-data.sh:/setup-test-data.sh
    depends_on:
      - namenode
      - datanode
    command: ["/setup-test-data.sh"]

volumes:
  namenode_data:
  datanode_data:

networks:
  default:
    name: hdfs-filemanager-test
